server:
  port: 8089
spring:
  application:
    name: shiro
  datasource:
    url: jdbc:mysql://116.63.138.138:3306/wan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    username: root
    password: ss1111
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    showSql: false
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
